name: Run Docker Image

on:
  workflow_dispatch:
    inputs:
      maximize_build_space:
        description: 'Free up space on the GitHub runner (default: no)'
        required: false
        default: 'no'
        type: choice
        options:
          - 'no'
          - 'yes'

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        if: ${{ github.event.inputs.maximize_build_space == 'yes' }}
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker image
        run: |
          docker network create my-network
          docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_IMAGE_TAG }}
          docker run --network my-network --hostname huggingdata-gh-runner -v /var/run/docker.sock:/var/run/docker.sock docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_IMAGE_TAG }}
